{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "85dfdb9a",
   "metadata": {},
   "source": [
    "Following the tutorial for [how to design a part in build123d](https://build123d.readthedocs.io/en/stable/tutorial_design.html)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "d22e2658",
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import (\n",
    "    Axis,\n",
    "    BuildLine,\n",
    "    BuildPart,\n",
    "    BuildSketch,\n",
    "    FilletPolyline,\n",
    "    Hole,\n",
    "    Locations,\n",
    "    MM,\n",
    "    Mode,\n",
    "    Plane,\n",
    "    Side,\n",
    "    SlotOverall,\n",
    "    extrude,\n",
    "    fillet,\n",
    "    make_face,\n",
    "    mirror,\n",
    "    offset,\n",
    ")\n",
    "from ocp_vscode import show\n",
    "\n",
    "# Parameters for the bracket\n",
    "thickness = 3 * MM\n",
    "width = 25 * MM\n",
    "length = 50 * MM\n",
    "height = 25 * MM\n",
    "hole_diameter = 5 * MM\n",
    "slot_length = 20 * MM\n",
    "bend_radius = 5 * MM\n",
    "fillet_radius = 2 * MM\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c2dd62f3",
   "metadata": {},
   "source": [
    "1. Create a line using `FilletPolyline` with two parts and a curved corner\n",
    "1. Turn the line into a 2D shape using offset, which gives the line \"thickness\"\n",
    "1. Mirror the 2D corner shape to create a \"U\" shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "dfcc9e07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-c\n"
     ]
    }
   ],
   "source": [
    "with BuildSketch() as sketch:\n",
    "    with BuildLine() as profile:\n",
    "        FilletPolyline(\n",
    "            (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "        )\n",
    "        offset(amount=thickness, side=Side.LEFT)\n",
    "    make_face()\n",
    "    mirror(about=Plane.YZ)\n",
    "\n",
    "show(sketch)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1d4f2963",
   "metadata": {},
   "source": [
    "1. Take the 2D object from the previous step and use `extrude` to extend it out into a 3D object.\n",
    "1. Use mirror again, but this time to copy the object, so it's symmetrical (it already was, but worth checking)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "224dc94b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as bracket:\n",
    "    with BuildSketch() as sketch:\n",
    "        with BuildLine() as profile:\n",
    "            FilletPolyline(\n",
    "                (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "            )\n",
    "            offset(amount=thickness, side=Side.LEFT)\n",
    "        make_face()\n",
    "        mirror(about=Plane.YZ)\n",
    "    extrude(amount=width / 2)\n",
    "    mirror(about=Plane.XY)\n",
    "\n",
    "show(bracket)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41086332",
   "metadata": {},
   "source": [
    "1. Select sharp corners at the tips of the U-shape of the bracket\n",
    "1. Fillet the corners"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "a4f87248",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "\n",
    "with BuildPart() as bracket:\n",
    "    with BuildSketch() as sketch:\n",
    "        with BuildLine() as profile:\n",
    "            FilletPolyline(\n",
    "                (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "            )\n",
    "            offset(amount=thickness, side=Side.LEFT)\n",
    "        make_face()\n",
    "        mirror(about=Plane.YZ)\n",
    "    extrude(amount=width / 2)\n",
    "    mirror(about=Plane.XY)\n",
    "    corners = bracket.edges().filter_by(Axis.X).group_by(Axis.Y)[-1]\n",
    "    fillet(corners, fillet_radius)\n",
    "\n",
    "show(bracket)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "23c0ea2b",
   "metadata": {},
   "source": [
    "Still working inside the bracket part:\n",
    "1. Use Locations to select the ends of the bracket\n",
    "1. Cut holes in the centre of the ends of the bracket"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "47ce834b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as bracket:\n",
    "    with BuildSketch() as sketch:\n",
    "        with BuildLine() as profile:\n",
    "            FilletPolyline(\n",
    "                (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "            )\n",
    "            offset(amount=thickness, side=Side.LEFT)\n",
    "        make_face()\n",
    "        mirror(about=Plane.YZ)\n",
    "    extrude(amount=width / 2)\n",
    "    mirror(about=Plane.XY)\n",
    "    corners = bracket.edges().filter_by(Axis.X).group_by(Axis.Y)[-1]\n",
    "    fillet(corners, fillet_radius)\n",
    "\n",
    "    with Locations(bracket.faces().sort_by(Axis.X)[-1]):\n",
    "        Hole(hole_diameter / 2)\n",
    "\n",
    "show(bracket)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06d402e6",
   "metadata": {},
   "source": [
    "Finally, still working on the bracket Part, cut out the slot\n",
    "1. Create a 2D Sketch using SlotOverall (I replaced the hard-coded dimension of the slot with a variable)\n",
    "1. Use `extrude` with the mode set to substract to cut the slot from the chosen wall"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "da611565",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as bracket:\n",
    "    with BuildSketch() as sketch:\n",
    "        with BuildLine() as profile:\n",
    "            FilletPolyline(\n",
    "                (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "            )\n",
    "            offset(amount=thickness, side=Side.LEFT)\n",
    "        make_face()\n",
    "        mirror(about=Plane.YZ)\n",
    "    extrude(amount=width / 2)\n",
    "    mirror(about=Plane.XY)\n",
    "    corners = bracket.edges().filter_by(Axis.X).group_by(Axis.Y)[-1]\n",
    "    fillet(corners, fillet_radius)\n",
    "\n",
    "    with Locations(bracket.faces().sort_by(Axis.X)[-1]):\n",
    "        Hole(hole_diameter / 2)\n",
    "\n",
    "    with BuildSketch(bracket.faces().sort_by(Axis.Y)[0]):\n",
    "        SlotOverall(slot_length * MM, hole_diameter)\n",
    "    extrude(amount=-thickness, mode=Mode.SUBTRACT)\n",
    "show(bracket)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
