{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "85dfdb9a",
   "metadata": {},
   "source": [
    "Following the tutorial for [how to design a part in build123d](https://build123d.readthedocs.io/en/stable/tutorial_design.html)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d22e2658",
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import (\n",
    "    BuildLine,\n",
    "    BuildSketch,\n",
    "    FilletPolyline,\n",
    "    MM,\n",
    "    Plane,\n",
    "    Side,\n",
    "    make_face,\n",
    "    mirror,\n",
    "    offset,\n",
    ")\n",
    "from ocp_vscode import show\n",
    "height = 40 * MM\n",
    "length = 60 * MM\n",
    "thickness = 10 * MM\n",
    "bend_radius = 5 * MM"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dfcc9e07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using port 3939\n",
      "Jupyter kernel running\n",
      "Jupyter connection file path written to /home/james/.ocpvscode\n",
      "-+\n"
     ]
    }
   ],
   "source": [
    "with BuildSketch() as sketch:\n",
    "    with BuildLine() as profile:\n",
    "        FilletPolyline(\n",
    "            (0, 0), (length / 2, 0), (length / 2, height), radius=bend_radius\n",
    "        )\n",
    "        offset(amount=thickness, side=Side.LEFT)\n",
    "    make_face()\n",
    "    mirror(about=Plane.YZ)\n",
    "\n",
    "show(sketch)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
